name: Graduate Beta

on:
  push:
    branches:
      - develop

jobs:
  graduate_beta:
    name: Graduate Beta
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Set up NPM auth
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm config set \
            '//registry.npmjs.org/:_authToken' \
            "${NPM_TOKEN}"
      - name: Set up Git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name 'Jake Elder'
          git config user.email 'jake@jakes.world'
          git config user.password ${GITHUB_TOKEN}
      - name: Version
        run: |
          npx lerna version --conventional-graduate --yes
          git push --force origin $GITHUB_HEAD_REF
      - name: Publish
        run: npx lerna publish from-package --yes
