name: Publish Beta

on:
  pull_request:
    branches:
      - develop

jobs:
  publish_packages_to_npm:
    name: Publish packages to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Set up NPM auth
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm config set \
            '//registry.npmjs.org/:_authToken' \
            "${NPM_TOKEN}"
      - name: Set up Git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name 'Jake Elder'
          git config user.email 'jake@jakes.world'
          git config user.password ${GITHUB_TOKEN}
      - name: Version
        run: |
          npx lerna version \
            --conventional-prerelease \
            --preid beta \
            --no-changelog \
            --amend \
            --yes
          git push --force origin $GITHUB_HEAD_REF
      - name: Publish
        run: npx lerna publish from-package --yes

  deploy_strapi:
    name: Deploy Strapi
    runs-on: ubuntu-latest
    needs: publish_packages_to_npm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Git log
        run: git log
      - name: Push to Heroku
        run: |
          git remote add heroku git@heroku.com:tenjin-cms-stage.git
          subtree=`
            git subtree split \
              --prefix packages/tenjin-cms \
              HEAD
          `
          git push --force heroku ${subtree}:refs/heads/master

  deploy_storybook:
    name: Deploy Storybook
    runs-on: ubuntu-latest
    needs: publish_packages_to_npm
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Get Yarn Cache Dir
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Pull changes
        run: git log
      - name: Install NPM Deps
        run: yarn install
      - name: Build
        run: |
          npx lerna run build \
            --scope @mindfulstudio/tenjin-ui \
            --stream
      - name: Deploy
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_UI_PROJECT_ID_STAGE }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          npx lerna run deploy \
            --scope @mindfulstudio/tenjin-ui \
            --stream

  deploy_next_js_app:
    name: Deploy Next.js app
    needs: publish_packages_to_npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Git log
        run: git log
      - name: Deploy Build
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_APP_PROJECT_ID_STAGE }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          npx lerna run deploy \
            --scope @mindfulstudio/tenjin-app \
            --stream
